/* Project	For NDNS RP correspondence anlaysis about time slot and food group for 
** Different Diabetes status Aug 17 2019   
*/

/*libname PROJ "\\tsclient\Documents\CA-NDNSRP" ;*/
libname PROJ  "\\tsclient\Documents\CA-NDNSRP";



PROC IMPORT 
			DATAFILE = "\\tsclient\Documents\CA-NDNSRP\TFood.csv"
			DBMS = csv
			OUT = PROJ.NDNSRP
			REPLACE; 
RUN;




/* CREATE BINARY INDICATORS FOR THE LOGISTIC REGRESSION */

DATA TEST; 
			SET  PROJ.NDNSRP; 
			YESPUDDING = 0; 
			IF MAINFOODGROUPCODE = 9 THEN YESPUDDING = 1;
			AGECAT = 0; 
			IF AGE > 18 & AGE < 41 THEN AGECAT = 1;
			IF AGE >= 41 & AGE < 51 THEN AGECAT = 2; 
			IF AGE >= 51 & AGE < 61 THEN AGECAT = 3; 
			IF AGE >= 61 & AGE < 71 THEN AGECAT = 4; 
			IF AGE >= 71 & AGE < 81 THEN AGECAT = 5; 
			IF AGE >= 81                   THEN AGECAT = 6; 
RUN;	


/*	----------------------------------*/
/* Exploratory analysis                               */
/*	----------------------------------*/
		
/* what does the data contain */

PROC CONTENTS  DATA = TEST; 
RUN; 

/* Print the data set */

PROC PRINT DATA = TEST (OBS = 30);
RUN;


/* tabulate timeslots */

PROC FREQ DATA = TEST;
	TABLES TIME3G*DM4CAT;
RUN;


PROC FREQ DATA = TEST;
	TABLES DM4CAT*MealTimeSlot;
RUN;

/* multilevel logistic regression using GEE  EXCHANGE COVARIANCE MATRIX */ 

PROC GENMOD DATA =  TEST DESCENDING;
	CLASS SERIALI YESPUDDING   TIME3G DM4CAT(REF = "0") SEX(REF = "1") AGECAT NSSEC8 AREA;
	MODEL YESPUDDING = TIME3G DM4CAT SEX AGECAT NSSEC8/ ALPHA = 0.01 DIST = B TYPE3 WALD; 
	WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI * AREA / TYPE = EXCH; 
	TITLE "PUDDING GEE "; 
	ESTIMATE "PUDDING EVENING VS MORNING" TIME3G 0 1 -1 /ALPHA = 0.01 EXP; 
	ESTIMATE "PUDDING EVENING VS AFTERNOON" TIME3G -1 1 0 /ALPHA = 0.01 EXP;
	LSMEANS DM4CAT TIME3G / PDIFF EXP;
RUN;



/* multilevel logistic regression using GEE  UNSTR COVARIANCE MATRIX */ 

PROC GENMOD DATA =  TEST DESCENDING;
	CLASS SERIALI YESPUDDING   TIME3G DM4CAT(REF = "0") SEX(REF = "1") AGECAT NSSEC8 AREA;
	MODEL YESPUDDING = TIME3G DM4CAT SEX AGECAT NSSEC8/ ALPHA = 0.01 DIST = B TYPE3 WALD; 
	WHERE NSSEC8 > 0 & DM4CAT ~= "NA";  
	REPEATED SUBJECT = SERIALI * AREA / TYPE = UNSTR; 
	TITLE "PUDDING GEE "; 
	ESTIMATE "PUDDING EVENING VS MORNING" TIME3G 0 1 -1 /ALPHA = 0.01 EXP; 
	ESTIMATE "PUDDING EVENING VS AFTERNOON" TIME3G -1 1 0 /ALPHA = 0.01 EXP;
	LSMEANS DM4CAT TIME3G / PDIFF EXP;
RUN;


/* RUN SUBJECT-SPECIFIC ANALYSIS    */
/* RANDOM INTERCEPT ONLY   */ 


PROC GLIMMIX DATA = TEST METHOD = QUAD(QCHECK);
	CLASS  SERIALI  TIME3G DM4CAT(REF = "0") SEX(REF = "1") AGECAT NSSEC8 AREA;
		MODEL YESPUDDING (DESCENDING) =    TIME3G DM4CAT SEX AGECAT NSSEC8/ ALPHA = 0.01 DIST = B S; 
		RANDOM INTERCEPT  / SUBJECT = SERIALI; 
		ESTIMATE "PUDDING EVENING VS MORNING" TIME3G 0 1 -1 /ALPHA = 0.01 EXP; 
		ESTIMATE "PUDDING EVENING VS AFTERNOON" TIME3G -1 1 0 /ALPHA = 0.01 EXP;
RUN;





/* multilevel logistic regression using GEE WITH INTERATCION BETWEEN DM4CAT AND TIME3G */ 

PROC GENMOD DATA =  TEST DESCENDING;
	CLASS SERIALI YESPUDDING   TIME3G DM4CAT(REF = "0") SEX(REF = "1") AGECAT NSSEC8 AREA;
	MODEL YESPUDDING = TIME3G DM4CAT TIME3G*DM4CAT / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
	TITLE "PUDDING GEE "; 
RUN;

PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME3G DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESPUDDING = TIME3G DM4CAT TIME3G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
	TITLE "PUDDING GEE "; 
RUN;


PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESPUDDING = TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
	TITLE "PUDDING GEE "; 
RUN;



/* CHANGE AGECAT INTO AGE AS CONT. NSSEC8 INTO 3 CATEGORIES */

DATA TEST; 
			SET  PROJ.NDNSRP; 
			YESPUDDING = 0; 
			IF MAINFOODGROUPCODE = 9 THEN YESPUDDING = 1;
			YESREGSOFT = 0;
			IF MAINFOODGROUPCODE = 57 THEN YESREGSOFT = 1; 
			YESSPIRIT = 0;
            IF MAINFOODGROUPCODE = 47 THEN YESSPIRIT = 1; 
			YESBEER = 0; 
            IF MAINFOODGROUPCODE = 49 THEN YESBEER = 1; 
            YESCHOCO = 0; 
			IF MAINFOODGROUPCODE = 44 THEN YESCHOCO = 1;
			YESSUGAR = 0; 
			IF MAINFOODGROUPCODE = 43 THEN YESSUGAR = 1;
			YESNUTS = 0; 
			IF MAINFOODGROUPCODE = 56 THEN YESNUTS = 1;
			YESBISCUITS = 0; 
			IF MAINFOODGROUPCODE = 7 THEN YESBISCUITS = 1;
			YESBURGERS = 0; 
			IF MAINFOODGROUPCODE = 29 THEN YESBURGERS = 1;
			YESICECREAM = 0; 
			IF MAINFOODGROUPCODE = 53 THEN YESICECREAM = 1;
			YESDIETSOFT = 0; 
			IF MAINFOODGROUPCODE = 58 THEN YESDIETSOFT = 1;
			YESCRISP = 0; 
			IF MAINFOODGROUPCODE = 42 THEN YESCRISP = 1; 
			YESBEER = 0; 
			IF MAINFOODGROUPCODE = 49 THEN YESBEER = 1; 
			YESWINE = 0; 
			IF MAINFOODGROUPCODE = 48 THEN YESWINE = 1;
            YESSPIRITS = 0; 
			IF MAINFOODGROUPCODE = 47 THEN YESSPIRITS = 1;
            YESJUICE = 0; 
			IF MAINFOODGROUPCODE = 45 THEN YESJUICE = 1; 
			NSSEC3 = 1; 
			IF NSSEC8 = 3 | NSSEC8 = 4 THEN NSSEC3 = 2; 
			IF NSSEC8 = 5 | NSSEC8 = 6 | NSSEC8 = 7 | NSSEC8 = 8 THEN NSSEC3 = 3; 
			TIME2G = 1; 
			IF TIME3G = "Afternoon" | TIME3G = "Morning" THEN TIME2G = 0;
RUN;	

/**************************/
/* PUDDING */ 
/**************************/

/* time3g */ 

PROC GENMOD DATA =  TEST DESCENDING;
	CLASS SERIALI YESPUDDING   TIME3G(REF = "Morning") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESPUDDING = TIME3G DM4CAT SEX AGE NSSEC3/ ALPHA = 0.01 DIST = B TYPE3 WALD; 
	WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI * AREA / TYPE = EXCH; 
	TITLE "PUDDING GEE "; 
	ESTIMATE "PUDDING EVENING VS MORNING" TIME3G 0 1 -1 /ALPHA = 0.01 EXP; 
	ESTIMATE "PUDDING EVENING VS AFTERNOON" TIME3G -1 1 0 /ALPHA = 0.01 EXP;
	LSMEANS DM4CAT TIME3G / PDIFF EXP;
RUN;


/* time2g */ 
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESPUDDING = TIME2G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = EXCH;
    ESTIMATE "PUDDING EVENING VS AFTERNOON/MORNING" TIME2G 1 -1 /ALPHA = 0.01 EXP; 
	TITLE "PUDDING GEE "; 
RUN;




PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESPUDDING = TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
    ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  
	ESTIMATE "DM4cat = 4 (non-diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 0 1 0 0 0 -1 /ALPHA = 0.01 exp;  
	TITLE "PUDDING GEE "; 
RUN;

/**************************/
/* SPIRIT */ 
/**************************/

/* time3g */
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME3G(REF = "Morning") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESSPIRIT = TIME3G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
   	ESTIMATE "SPIRIT EVENING VS MORNING" TIME3G 0 1 -1 /ALPHA = 0.01 EXP; 
	ESTIMATE "SPIRIT EVENING VS AFTERNOON" TIME3G -1 1 0 /ALPHA = 0.01 EXP;
	TITLE "SPIRIT GEE "; 
RUN;

 /* time2g */ 
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESSPIRIT = TIME2G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
    ESTIMATE "SPIRIT EVENING VS AFTERNOON/MORNING" TIME2G 1 -1 /ALPHA = 0.01 EXP; 
	/*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
	TITLE "SPIRIT GEE "; 
RUN;




PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESSPIRIT = TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
    ESTIMATE "DM4cat = 1 (prediabetes), SPIRIT EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), SPIRIT EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), SPIRIT EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  
	ESTIMATE "DM4cat = 4 (non-diabetes), SPIRIT EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 0 1 0 0 0 -1 /ALPHA = 0.01 exp;  
	TITLE "SPIRIT GEE "; 
RUN;



/**************************/
/* YESCHOCO */ 
/**************************/

	 /* time2g */ 				  
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESCHOCO = TIME2G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
    ESTIMATE "Choco EVENING VS AFTERNOON/MORNING" TIME2G 1 -1 /ALPHA = 0.01 EXP; 
	TITLE "YESCHOCO GEE "; 
RUN;


PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESCHOCO = TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
    ESTIMATE "DM4cat = 1 (prediabetes), YESCHOCO EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), YESCHOCO EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), YESCHOCO EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  
	ESTIMATE "DM4cat = 4 (non-diabetes), YESCHOCO EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 0 1 0 0 0 -1 /ALPHA = 0.01 exp;  
	TITLE "YESCHOCO GEE "; 
RUN;



/**************************/
/* YESBEER */ 
/**************************/



/* time2g */ 									  
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESBEER = TIME2G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
    ESTIMATE "BEER EVENING VS AFTERNOON/MORNING" TIME2G 1 -1 /ALPHA = 0.01 EXP; 
	TITLE "BEER GEE "; 
RUN;

/* time3g */ 			
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME3G(REF = "Morning") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESBEER = TIME3G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
	TITLE "BEER GEE "; 
RUN;

PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESBEER = TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
    ESTIMATE "DM4cat = 1 (prediabetes), BEER EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), BEER EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), BEER EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  
	ESTIMATE "DM4cat = 4 (non-diabetes), BEER EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 0 1 0 0 0 -1 /ALPHA = 0.01 exp;  
	TITLE "BEER GEE "; 
RUN;




/**************************/
/* YESSUGAR */ 
/**************************/

					  
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESSUGAR = TIME2G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
    ESTIMATE "YESSUGAR EVENING VS AFTERNOON/MORNING" TIME2G 1 -1 /ALPHA = 0.01 EXP; 
	TITLE "YESSUGAR GEE "; 
RUN;


PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME3G(REF = "Morning") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESSUGAR = TIME3G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
	TITLE "YESSUGAR GEE "; 
RUN;

PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESSUGAR = TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
    ESTIMATE "DM4cat = 1 (prediabetes), YESSUGAR EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.05 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), YESSUGAR EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.05 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), YESSUGAR YESSUGAR VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.05 exp;  
	ESTIMATE "DM4cat = 4 (non-diabetes), YESSUGAR EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 0 1 0 0 0 -1 /ALPHA = 0.01 exp;  
	TITLE "YESSUGAR GEE "; 
RUN;



/**************************/
/* YESREGSOFT */ 
/**************************/

					  
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESREGSOFT = TIME2G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
    ESTIMATE "YESREGSOFT EVENING VS AFTERNOON/MORNING" TIME2G 1 -1 /ALPHA = 0.01 EXP; 
	TITLE "YESREGSOFT GEE "; 
RUN;


PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME3G(REF = "Morning") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESREGSOFT = TIME3G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
	TITLE "YESREGSOFT GEE "; 
RUN;

PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESREGSOFT = TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
    ESTIMATE "DM4cat = 1 (prediabetes), YESREGSOFT EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), YESREGSOFT EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), YESREGSOFT EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  
	ESTIMATE "DM4cat = 4 (non-diabetes), YESREGSOFT EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 0 1 0 0 0 -1 /ALPHA = 0.01 exp;  
	TITLE "YESREGSOFT GEE "; 
RUN;





/**************************/
/* ICECREAM  */ 
/**************************/

					  
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESICECREAM = TIME2G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
    ESTIMATE "YESICECREAM EVENING VS AFTERNOON/MORNING" TIME2G 1 -1 /ALPHA = 0.01 EXP; 
	TITLE "YESICECREAM GEE "; 
RUN;


PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESICECREAM = TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
    ESTIMATE "DM4cat = 1 (prediabetes), YESICECREAM EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), YESICECREAM EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), YESICECREAM EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  
	ESTIMATE "DM4cat = 4 (non-diabetes), YESICECREAM EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 0 1 0 0 0 -1 /ALPHA = 0.01 exp;  
	TITLE "YESICECREAM GEE "; 
RUN;








/**************************/
/* CRISPS  */ 
/**************************/

					  
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESCRISP = TIME2G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
    ESTIMATE "YESCRISP EVENING VS AFTERNOON/MORNING" TIME2G 1 -1 /ALPHA = 0.01 EXP; 
	TITLE "YESCRISP GEE "; 
RUN;


PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESCRISP = TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
    ESTIMATE "DM4cat = 1 (prediabetes), YESCRISP EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), YESCRISP EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), YESCRISP EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  
	ESTIMATE "DM4cat = 4 (non-diabetes), YESCRISP EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 0 1 0 0 0 -1 /ALPHA = 0.01 exp;  
	TITLE "YESCRISP GEE "; 
RUN;




/* YESNUTS */ 


					  
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESNUTS = TIME2G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
	TITLE "YESNUTS GEE "; 
RUN;


PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME3G(REF = "Morning") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESNUTS = TIME3G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
	TITLE "YESNUTS GEE "; 
RUN;

PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESNUTS = TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
    ESTIMATE "DM4cat = 1 (prediabetes), YESNUTS EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), YESNUTS EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING YESNUTS VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  
	TITLE "YESNUTS GEE "; 
RUN;




/* YESBISCUITS */ 


					  
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESBISCUITS = TIME2G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
    ESTIMATE "YESBISCUITS EVENING VS AFTERNOON/MORNING" TIME2G 1 -1 /ALPHA = 0.01 EXP; 
	TITLE "YESBISCUITS GEE "; 
RUN;


PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME3G(REF = "Morning") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESBISCUITS = TIME3G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
	TITLE "YESBISCUITS GEE "; 
RUN;

PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESBISCUITS = TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
    ESTIMATE "DM4cat = 1 (prediabetes), YESBISCUITS EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), YESBISCUITS EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes),  YESBISCUITS EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  
	ESTIMATE "DM4cat = 4 (non-diabetes), YESBISCUITS EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 0 1 0 0 0 -1 /ALPHA = 0.01 exp;  
	TITLE "YESBISCUITS GEE "; 
RUN;




/* YESICECREAM */ 


					  
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESICECREAM = TIME2G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
	TITLE "YESICECREAM GEE "; 
RUN;


PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME3G(REF = "Morning") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESICECREAM = TIME3G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
	TITLE "YESICECREAM GEE "; 
RUN;

PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESICECREAM = TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
    ESTIMATE "DM4cat = 1 (prediabetes), YESICECREAM EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.05 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), YESICECREAM EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.05 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), YESICECREAM EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.05 exp;  
	TITLE "YESBISCUITS GEE "; 
RUN;





/* YESBURGERS */ 


					  
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESBURGERS = TIME2G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
	TITLE "YESBURGERS GEE "; 
RUN;


PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME3G(REF = "Morning") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESBURGERS = TIME3G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
	TITLE "YESBURGERS GEE "; 
RUN;

PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESBURGERS = TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
    ESTIMATE "DM4cat = 1 (prediabetes), YESBURGERS EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), YESBURGERS EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes),  YESBURGERS EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  
	TITLE "YESBURGERS GEE "; 
RUN;



/* YESDIETSOFT */ 


					  
PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESDIETSOFT = TIME2G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
	TITLE "YESDIETSOFT GEE "; 
RUN;


PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME3G(REF = "Morning") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESDIETSOFT = TIME3G DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
  /*  ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  */
	TITLE "YESDIETSOFT GEE "; 
RUN;

PROC GENMOD DATA =  TEST DESCENDING;
	CLASS  SERIALI  TIME2G(REF = "0") DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
	MODEL YESDIETSOFT = TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3 / ALPHA = 0.01 DIST = B TYPE3; 
			WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
	REPEATED SUBJECT = SERIALI*AREA / TYPE = IND; 
    ESTIMATE "DM4cat = 1 (prediabetes), YESDIETSOFT EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.05 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), YESDIETSOFT EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.05 exp; 
	ESTIMATE "DM4cat = 3 (diabetes),  YESDIETSOFT EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.05 exp;  
	TITLE "YESDIETSOFT GEE "; 
RUN;





		/* RUN SUBJECT-SPECIFIC ANALYSIS    */
/* RANDOM INTERCEPT ONLY WITH INTERATCION BETWEEN DM4CAT AND TIME3G   */ 



PROC GLIMMIX DATA = TEST METHOD = QUAD(QCHECK);
	CLASS  SERIALI  TIME3G DM4CAT(REF = "0") SEX(REF = "1") AGECAT NSSEC8 AREA;
		MODEL YESPUDDING (DESCENDING) =    TIME3G DM4CAT TIME3G*DM4CAT  SEX AGECAT NSSEC8/ ALPHA = 0.01 DIST = B S; 
		WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
		RANDOM INTERCEPT  / SUBJECT = SERIALI*AREA; 
		/*ESTIMATE "PUDDING EVENING VS MORNING in prediabetes" TIME3G 0 1 -1 TIME3G*DM4CAT 0 0 0 0 0 1 0 0 0 0 -1 0 0 0 0 /ALPHA = 0.01 EXP; 
		ESTIMATE "PUDDING EVENING VS MORNING in UNDIAG" TIME3G 0 1 -1 TIME3G*DM4CAT 0 0 0 0 0 0 1 0 0 0 0 -1 0 0 0 /ALPHA = 0.01 EXP; */
RUN;





PROC FREQ DATA = TEST;
	TABLES TIME3G*NSSEC3;
	TABLES TIME2G*DM4CAT;
RUN;


PROC GLIMMIX DATA = TEST METHOD = QUAD(QCHECK);
	CLASS  SERIALI  TIME3G DM4CAT(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA;
		MODEL YESPUDDING (DESCENDING) =    TIME3G DM4CAT TIME3G*DM4CAT  SEX AGE NSSEC3/ ALPHA = 0.01 DIST = B S; 
		WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
		RANDOM INTERCEPT  / SUBJECT = SERIALI*AREA; 
		/*ESTIMATE "PUDDING EVENING VS MORNING in prediabetes" TIME3G 0 1 -1 TIME3G*DM4CAT 0 0 0 0 0 1 0 0 0 0 -1 0 0 0 0 /ALPHA = 0.01 EXP; 
		ESTIMATE "PUDDING EVENING VS MORNING in UNDIAG" TIME3G 0 1 -1 TIME3G*DM4CAT 0 0 0 0 0 0 1 0 0 0 0 -1 0 0 0 /ALPHA = 0.01 EXP; */
RUN;


PROC GLIMMIX DATA = TEST METHOD = QUAD(QCHECK);
	CLASS  SERIALI  TIME2G DM4CAT SEX(REF = "1") NSSEC3(REF = "1") AREA ;
		MODEL YESPUDDING (DESCENDING) =    TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3/ ALPHA = 0.01 DIST = B S; 
		WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
		RANDOM INTERCEPT  / SUBJECT = SERIALI*AREA;
    ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G -1 1 TIME2G*DM4CAT 0 -1 0 0 0 1 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G -1 1 TIME2G*DM4CAT 0 0 -1 0 0 0 1 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G -1 1 TIME2G*DM4CAT 0 0 0 -1 0 0 0 1  /ALPHA = 0.01 exp;  
		/*CONTRAST "PUDDING EVENING VS MORNING/AFTERNOON in prediabetes" TIME2G 1 0   TIME2G*DM4CAT 1 0 0 0  /  EST; 
		ESTIMATE "PUDDING EVENING VS MORNING in UNDIAG" TIME3G 0 1 -1 TIME3G*DM4CAT 0 0 0 0 0 0 1 0 0 0 0 -1 0 0 0 /ALPHA = 0.01 EXP; */
RUN;


PROC GLIMMIX DATA = TEST METHOD = QUAD(QCHECK);
	CLASS  SERIALI  TIME2G(REF = "0")  DM4CAT(REF = "0")  SEX(REF = "1") NSSEC3(REF = "1") AREA ;
		MODEL YESPUDDING (DESCENDING) =    TIME2G DM4CAT TIME2G*DM4CAT  SEX AGE NSSEC3/ ALPHA = 0.01 DIST = B S; 
		WHERE NSSEC8 > 0 & DM4CAT ~= "NA"; 
		RANDOM INTERCEPT  / SUBJECT = SERIALI*AREA;
    ESTIMATE "DM4cat = 1 (prediabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT  1 0 0 0  -1 0 0 0  /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 2 (undiagdiabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 1 0 0 0  -1 0 0 /ALPHA = 0.01 exp; 
	ESTIMATE "DM4cat = 3 (diabetes), PUDDING EVENING VS MORNING/AFTERNOON" TIME2G 1 -1 TIME2G*DM4CAT 0 0 1 0 0 0 -1 0 /ALPHA = 0.01 exp;  
		/*CONTRAST "PUDDING EVENING VS MORNING/AFTERNOON in prediabetes" TIME2G 1 0   TIME2G*DM4CAT 1 0 0 0  /  EST; 
		ESTIMATE "PUDDING EVENING VS MORNING in UNDIAG" TIME3G 0 1 -1 TIME3G*DM4CAT 0 0 0 0 0 0 1 0 0 0 0 -1 0 0 0 /ALPHA = 0.01 EXP; */
RUN;



/* STRATIFICATION ANALYSIS  IN PREDIABETES*/ 

PROC GLIMMIX DATA = TEST METHOD = QUAD(QCHECK);
	CLASS  SERIALI  TIME2G(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA ;
		MODEL YESPUDDING (DESCENDING) =    TIME2G  SEX AGE NSSEC3/ ALPHA = 0.01 DIST = B S; 
		WHERE NSSEC8 > 0 & DM4CAT ~= "NA" & DM4CAT = "1"; 
		RANDOM INTERCEPT  / SUBJECT = SERIALI*AREA; 
		/*CONTRAST "PUDDING EVENING VS MORNING/AFTERNOON in prediabetes" TIME2G 1 0   TIME2G*DM4CAT 1 0 0 0  /  EST; 
		ESTIMATE "PUDDING EVENING VS MORNING in UNDIAG" TIME3G 0 1 -1 TIME3G*DM4CAT 0 0 0 0 0 0 1 0 0 0 0 -1 0 0 0 /ALPHA = 0.01 EXP; */
RUN;


/* STRATIFICATION ANALYSIS  IN UNDIAGNOSED */ 

PROC GLIMMIX DATA = TEST METHOD = QUAD(QCHECK);
	CLASS  SERIALI  TIME2G(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA ;
		MODEL YESPUDDING (DESCENDING) =    TIME2G  SEX AGE NSSEC3/ ALPHA = 0.01 DIST = B S; 
		WHERE NSSEC8 > 0 & DM4CAT ~= "NA" & DM4CAT = "2"; 
		RANDOM INTERCEPT  / SUBJECT = SERIALI*AREA; 
		/*CONTRAST "PUDDING EVENING VS MORNING/AFTERNOON in prediabetes" TIME2G 1 0   TIME2G*DM4CAT 1 0 0 0  /  EST; 
		ESTIMATE "PUDDING EVENING VS MORNING in UNDIAG" TIME3G 0 1 -1 TIME3G*DM4CAT 0 0 0 0 0 0 1 0 0 0 0 -1 0 0 0 /ALPHA = 0.01 EXP; */
RUN;



/* STRATIFICATION ANALYSIS  IN DM PATIENTS */ 

PROC GLIMMIX DATA = TEST METHOD = QUAD(QCHECK);
	CLASS  SERIALI  TIME2G(REF = "0") SEX(REF = "1") NSSEC3(REF = "1") AREA ;
		MODEL YESPUDDING (DESCENDING) =    TIME2G  SEX AGE NSSEC3/ ALPHA = 0.01 DIST = B S; 
		WHERE NSSEC8 > 0 & DM4CAT ~= "NA" & DM4CAT = "3"; 
		RANDOM INTERCEPT  / SUBJECT = SERIALI*AREA; 
		/*CONTRAST "PUDDING EVENING VS MORNING/AFTERNOON in prediabetes" TIME2G 1 0   TIME2G*DM4CAT 1 0 0 0  /  EST; 
		ESTIMATE "PUDDING EVENING VS MORNING in UNDIAG" TIME3G 0 1 -1 TIME3G*DM4CAT 0 0 0 0 0 0 1 0 0 0 0 -1 0 0 0 /ALPHA = 0.01 EXP; */
RUN;
